-- ==============================================================================
-- ⚠️ ARCHIVO DEPRECADO POR SEGURIDAD
-- ==============================================================================
-- La política de eliminación pública definida anteriormente en este archivo permitía
-- que cualquier usuario anónimo borrara archivos.
--
-- Por favor, utiliza la nueva política segura definida en `update_schema_v2.sql`
-- la cual restringe la eliminación de archivos únicamente a los administradores.
--
-- Si ya ejecutaste la política pública anterior, bórrala desde el editor SQL de Supabase con:
-- DROP POLICY IF EXISTS "Permitir eliminacion publica a pedidos" ON storage.objects;
-- ==============================================================================
